sudo: required
language: node_js
node_js:
  - "13"
services:
  - docker

install:
  - npm install

script:
  - echo "npm test"

deploy:
  provider: heroku
  api_key: $API_KEY
  app: tfm-api-repositorio
  on:
    branch: master