version: '3'
services:
    api:
        image: tonen100/api-restapimantics
        depends_on:
            - mongo
        restart: on-failure
        ports:
            - "8080:8080"
        environment:
            - URL_APP=${URL_API}
            - MONGO_HOSTNAME=mongo
            - MONGO_PORT=${DB_PORT}
            - MONGO_DB_NAME=API_Repository
            - VIRTUAL_HOST=api.${VIRTUAL_HOST}
            - VIRTUAL_PORT=${PORT}
    front:
        image: tonen100/front-restapimantics
        expose:
            - "${FRONT_PORT}"
        ports:
            - "${FRONT_PORT}:4000"
        depends_on:
            - api
        restart: on-failure
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=${FRONT_PORT}
    mongo:
        image: "mongo"
        command: --port ${DB_PORT}
networks:
    default:
        external:
            name: restapimantics
