@startuml "DC APIs Repositorio"
enum BusinessModel {
    Free
    FreeWithLimitations
    FreeTrialVersion
    FlatRateAllInclusive
    FlatRatesWithLimitations
    Billing
}

class Provider {
    name: String
    logo: Image
    description: String
    externalLinks: String[]
}

class RestApi {
   name: String
   logo: Image
   businessModels: BusinessModel[]
}

class Version {
    number: String // Semver
    description: String
    originalDocumentation: String
    oasDocumentation: Object //OASv3
    metadata: Object //WebAPI
    deprecated: Boolean = false
}

class User {
    username: String
    email: String
    password: String
}

class Explorer {
    description: String
    banned: Boolean = false
}

class Administrator {

}

class ContributionHistory {
    contribution_id: String
    date: DateTime
    action: ['ADD', 'EDIT', 'DELETE']
}

class Contribution {
    blacklisted: Boolean = false
    history: ContributionHistory
}

RestApi *-right- "0..*" Version
Provider o-right- "0..*" RestApi
User <|-- Administrator
User <|-- Explorer
Administrator --> Contribution: Blacklist
Administrator -left-> Explorer: Ban
Explorer --> Contribution: Add, edit, delete
Contribution <|-- Provider
Contribution <|-- RestApi
Contribution <|-- Version
@enduml